# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc


before_install:
    - sudo sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list && sudo apt-get update
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install qt5-default
    
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
